-- CREATES DATABASE 
DROP DATABASE IF EXISTS EMPLOYEE_TRACKER_DB;
CREATE DATABASE EMPLOYEE_TRACKER_DB;
-- TELLS MYSQL TO USE THE DATABASE
USE EMPLOYEE_TRACKER_DB;
-- CREATES TABLE FOR DEPARTMENTS
CREATE TABLE DEPARTMENT (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);
-- CREATES TABLE FOR ROLE
CREATE TABLE ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    SALARY DECIMAL (10,2) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (id) ON DELETE CASCADE
);
-- CREATES TABLE FOR EMPLOYEES
CREATE TABLE EMPLOYEE (
    id INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INT NOT NULL,
    MANAGER_ID INT,
    PRIMARY KEY (id),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(id) ON DELETE CASCADE,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(id) ON DELETE SET NULL
);